/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-nr_sync
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_NR_SYNC_API_H
#define INCLUDED_NR_SYNC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_nr_sync_EXPORTS
#define NR_SYNC_API __GR_ATTR_EXPORT
#else
#define NR_SYNC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_NR_SYNC_API_H */
